os: osx
osx_image: xcode10.1
language: cpp
install:
- brew install qt
- brew install opencv
- echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile
- export LDFLAGS="-L/usr/local/opt/qt/lib"
- export CPPFLAGS="-I/usr/local/opt/qt/include"
script: 
- cd imageProcess
- qmake
- make

